spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:mysql://64.227.30.87:3306/spring_batch?useUnicode=true&characterEncoding=utf8&useSSL=false&useLegacyDatetimeCode=false&serverTimezone=UTC&createDatabaseIfNotExist=true
    username: root
    password: 1234
    hikari:
      poolName: Hikari
      auto-commit: false
      data-source-properties:
        cachePrepStmts: true
        prepStmtCacheSize: 250
        prepStmtCacheSqlLimit: 2048
        useServerPrepStmts: true
  jpa:
    show-sql: true
config:
 base-value: 
  from-value: 300
  to-value: 500
  run-job: true
keycloak:  realm: microservice
  auth-server-url: http://64.227.30.87:8080/auth
  ssl-required: external
  resource: credit-api
  credentials:    secret: 28d7da30-e85e-4712-8deb-b8ba1d78d827
  use-resource-role-mappings: true
  bearer-only: true     
server:  port: 8083
  servlet:    context-path: /creditscore
  